### ISSUE TITLE
repository doesn't get remove from the profile after switching it to private and cannot be removed from the settings

### ISSUE THREAD

**Issue by azjezz** [thepracticaldev/dev.to#155]
# _TASK or Feature_
### Request or User Story
after adding a repository to my profile from the settings , i switched it to private and i can't remove it from the settings nor it have been removed automatically 
### Definition of Done
maybe the repository get removed automatically or can be removed from the settings.
# _BUG_
### Current Behavior
dev.to keeps on showing the repository that have been made private 
### Expected Behavior
private repository get removed automatically or can be removed from the settings 
### Screenshots
![image](https://user-images.githubusercontent.com/29315886/35818759-249b21b6-0aa1-11e8-9796-db0de4970776.png)

**Comment by Zhao-Andy** [comment]
Hey @azjezz, thanks for the heads up. We'll implement a better long term solution soon. I've removed your private repo from your profile now.

**Comment by azjezz** [comment]
@Zhao-Andy was this fixed ?

**Comment by Zhao-Andy** [comment]
@azjezz, don't believe this is fixed yet. I have a PR going for that page and will revisit it keeping this functionality in mind.

**Comment by azjezz** [comment]
good, i checked again and the behavior is still the same. 

i can't really think of way to fix this RN and i have little experience with ruby to open a PR ~ 

![screenshot from 2018-10-30 22-47-00](https://user-images.githubusercontent.com/29315886/47752846-e54bfb80-dc95-11e8-8535-a2ac0107a328.png)

**Comment by Zhao-Andy** [comment]
Ah, I actually think this is fixed, via this method: https://github.com/thepracticaldev/dev.to/blob/master/app/models/github_repo.rb#L24-L39

A few things to note:
1. We save GitHub repos into our database for performance.
2. We have a scheduled task that periodically updates the repos.
3. It looks for the GitHub repo based on the name.
4. If it doesn't find it, it'll destroy it from our database. Private repos cannot be accessed by us, so it sends the 404 error.

It's not an immediate effect though, and we should allow people to remove repos on their own. There is an issue for that (https://github.com/thepracticaldev/dev.to/issues/745) so for housekeeping purposes I'm going to close this one and leave that one open.
