### ISSUE TITLE
Cover upload error

### ISSUE THREAD

**Issue by Butonix** [thepracticaldev/dev.to#1935]
**Describe the bug**
Uploading a picture, getting an error.

**To Reproduce**

1. Go to 'http://localhost:3000/new'
2. Click on '/images/Cover Image' upload image

```
Heads up:
main_image: is not a valid URL
```

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/29381099/53654523-f6664280-3c5e-11e9-9f77-dd4e4e0dbaa7.png)

**Comment by jessleenyc** [comment]
I'm not able to reproduce this error.. I'm wondering if it's failing a validation like image size but throwing the wrong error message. Do you know how big the file was?

**Comment by Butonix** [comment]
> I'm not able to reproduce this error.. I'm wondering if it's failing a validation like image size but throwing the wrong error message. Do you know how big the file was?

I've tried different sizes and formats. The content is normally loaded. And the cover gives an error

**Comment by Zhao-Andy** [comment]
@Butonix is this only an issue in development and not `dev.to` (production)?

**Comment by jessleenyc** [comment]
great question, @Zhao-Andy - totally missed that!

**Comment by Butonix** [comment]
> @Butonix is this only an issue in development and not `dev.to` (production)?
Yes, it is in development, everything was normal before! Then you updated the code and started issuing such an error.

**Comment by desirottman** [comment]
@jessleenyc I get this intermittently (or other similar errors)and was just able to reproduce. Here's a screenshot of the image and console error:
![image](https://user-images.githubusercontent.com/11390786/54760237-a293ad00-4bbd-11e9-9e7c-363269cd8054.png)

and here's the file I was trying to upload: 
![markus-spiske-246212-unsplash](https://user-images.githubusercontent.com/11390786/54760246-a9babb00-4bbd-11e9-95a4-43f83a2ce707.jpg)

**Comment by rhymes** [comment]
@desirottman thanks for the bug report.

I believe it's going to be fixed by #2018 but in the meantime you should resize the image, the size limit is 4096x4096 and yours is 5760 × 3840

**Comment by maestromac** [comment]
Resolved with #2018 . Let us know if otherwise!

**Comment by Butonix** [comment]
> Resolved with #2018 . Let us know if otherwise!

I'm getting the wrong permission error, wrong url!
I do this on the local server. And still get this error
![Screenshot](https://user-images.githubusercontent.com/29381099/54841049-72442f80-4cdf-11e9-855e-39c2bb43c437.png)

**Comment by rhymes** [comment]
@Butonix on localhost files are saved to a directory on your computer, can you open a separate issue explaining all the steps that lead you to the error? Thank you!

**Comment by minhlucvan** [comment]
any update on this. I am facing the same issue on my development build
