### ISSUE TITLE
(x minutes ago) only shows every other post

### ISSUE THREAD

**Issue by nshusa** [thepracticaldev/dev.to#2012]
**Describe the bug**
Not every post says how long ago it has been posted.

**To Reproduce**
1. Click "Latest"
2. Look at the posts and it should say how long ago it was made every other post

**Expected behavior**
It should show on every post because it's awkward looking at the post above, or below to determine how long ago it was posted. This will drive OCD people crazy.

**Screenshots**
![(https://i.imgur.com/lStoCmy.png](https://i.imgur.com/lStoCmy.png)

**Desktop (please complete the following information):**

Chrome (latest)

**Comment by maestromac** [comment]
Thank you for reporting this issue @nshusa !

**Comment by keshavbiswa** [comment]
I think this issue is resolved in this pr #2015.

**Comment by maestromac** [comment]
yep it was. Thanks for the ping!

**Comment by chadalen** [comment]
This seems to be an issue still.
![image](https://user-images.githubusercontent.com/12568665/55017129-19fe7d80-4fbe-11e9-8a70-d6f0ed1d3c9c.png)

**Comment by Zhao-Andy** [comment]
@chadalen the text is only shown when the post was published within 24 hours ago.
