### ISSUE TITLE
Gist snippets need a page reload to show up

### ISSUE THREAD

**Issue by Einenlum** [thepracticaldev/dev.to#95]
# _BUG_

### Current Behavior

I encountered an issue with [one of my articles](https://dev.to/einenlum/lessons-learned-about-bus-factor-35-write-explicit-code-38l) which contains several gist snippets. Sometimes nothing show up if we don't reload the page.

### Additional Info (steps to replicate, device/browser, helpful links)

 The behavior can be checked if we arrive on the article from another part of the series. This behavior was encountered with Firefox 57 and Chromium 51.

### Screenshots

When I arrive on the page (bug): 
![before-reload](https://user-images.githubusercontent.com/5675200/31022464-27885a38-a539-11e7-890e-3479677e33bb.png)

After reloading the page:
![after-reload](https://user-images.githubusercontent.com/5675200/31022500-440232f6-a539-11e7-8ba0-5111986a271a.png)

*Screenshots taken while browsing with Firefox 57*

**Comment by Zhao-Andy** [comment]
Hmm I can't reproduce on Firefox 57, Chrome 61, Safari, or Edge. Think it might have been either a caching issue or just an issue retrieving the gist from GitHub at the time. 

If it happens again, could you look into dev tools and tell me if the HTML is there? Or if console is throwing any errors?

**Comment by maurobringolf** [comment]
**Possibly related:** I just wrote a draft post with an embedded gist and tried to use preview before saving the post. The gist did not show up and the console showed a 404 to this url:

https://gist.github.com/maurobringolf/b8840bccc4162ce423410b5ba3df6520%20.js

But the correct one from my post content is

https://gist.github.com/maurobringolf/b8840bccc4162ce423410b5ba3df6520

Saving the post without making any content changes (not publishing, just saving for the first time) fixed the problem.

**Comment by Zhao-Andy** [comment]
Hmm, think it's a separate issue with parsing the gist in preview form, but thanks for the heads up.

**Comment by Einenlum** [comment]
Thanks for your answer @Zhao-Andy .

Here is the DOM:

![dom](https://user-images.githubusercontent.com/5675200/31068805-ed126fd8-a759-11e7-8e62-d89070e368d4.png)

And here is the console:

![console](https://user-images.githubusercontent.com/5675200/31068816-f3fe5eba-a759-11e7-94cc-850fb9396e3d.png)

**Comment by maestromac** [comment]
This should be fixed, let me know if otherwise!

**Comment by Einenlum** [comment]
Seems to be ok now! Thank you @maestromac :)

**Comment by Einenlum** [comment]
Sorry @maestromac but it seems it's not fixed.

I tried to go to this article **on a fresh new install on my new computer**.

When I arrive, I have the bad gist (base6.php instead of base.php!) : 

![chromiumnormalbeforerefresh](https://user-images.githubusercontent.com/5675200/34544372-3ea25270-f0e6-11e7-9997-566af981d274.png)

If I refresh (without even clearing the cache), the right one appears : 

![chromiumnormalafterfresh](https://user-images.githubusercontent.com/5675200/34544399-547fffac-f0e6-11e7-8cb4-1b6708cbf32f.png)

After this, in the same articles, sometimes (randomly) some gists are missing.

![chromiummissingsnippets](https://user-images.githubusercontent.com/5675200/34544413-680be04a-f0e6-11e7-9cbc-277870a2687e.png)

If I'm lucky enough, after pressing F5, they appear.

![chromiumpresentsnippets](https://user-images.githubusercontent.com/5675200/34544425-7b040128-f0e6-11e7-8f2c-38a137ae9acb.png)

Both bugs appearing on elementary OS 0.4.1 Loki, **with Chromium** Browser Version 63.0.3239.84 (Official Build) **and Firefox** 57.0.3.

It's a very strange bug and very unfortunate cause it messes everything up in my article :(.

**Comment by Einenlum** [comment]
Actually there is now some error in console.

![console_error](https://user-images.githubusercontent.com/5675200/34544573-51eac866-f0e7-11e7-92ac-f526a4f44fdc.png)

**Comment by maestromac** [comment]
Thanks for reporting this! We will investigate.

**Comment by Einenlum** [comment]
It seems the issue was magically fixed? I hope it is, forever :). I close it.

**Comment by masquerade817** [comment]
> It seems the issue was magically fixed? I hope it is, forever :). I close it.

It wasn't! I'm still facing the issue!

**Comment by maestromac** [comment]
On which article are you seeing this @masquerade817 ?

**Comment by logeshpalani98** [comment]
This article code gist works in desktop browsers but in mobile browsers, how to fix this @maestromac
[https://logeshpalani.blogspot.com/2020/06/how-to-convert-base-64-to-image-in.html](https://logeshpalani.blogspot.com/2020/06/how-to-convert-base-64-to-image-in.html)

**Comment by maestromac** [comment]
@logeshpalani98 are you referring to the content on your own site? It seems to be working for me but I'm not sure how much I can assist you as this is not Dev.to related.
